// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/bank.go

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/iremsha/oapicodegen-example/internal/model"
)

// MockBankRepository is a mock of BankRepository interface.
type MockBankRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBankRepositoryMockRecorder
}

// MockBankRepositoryMockRecorder is the mock recorder for MockBankRepository.
type MockBankRepositoryMockRecorder struct {
	mock *MockBankRepository
}

// NewMockBankRepository creates a new mock instance.
func NewMockBankRepository(ctrl *gomock.Controller) *MockBankRepository {
	mock := &MockBankRepository{ctrl: ctrl}
	mock.recorder = &MockBankRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBankRepository) EXPECT() *MockBankRepositoryMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockBankRepository) FindAll() ([]model.Bank, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]model.Bank)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockBankRepositoryMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockBankRepository)(nil).FindAll))
}

// FindByID mocks base method.
func (m *MockBankRepository) FindByID(id int64) (*model.Bank, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*model.Bank)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockBankRepositoryMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockBankRepository)(nil).FindByID), id)
}

// Save mocks base method.
func (m *MockBankRepository) Save(bank *model.Bank) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", bank)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockBankRepositoryMockRecorder) Save(bank interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockBankRepository)(nil).Save), bank)
}
