paths:
  /api/v1/pets/:
    get:
      tags:
        - pets
      summary: Get List
      operationId: get_list_api_v1_pets__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Pet'
                type: array
                title: Response Get List Api V1 Pets  Get
    put:
      tags:
        - pets
      summary: Update
      operationId: update_api_v1_pets__put
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetPayload'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    post:
      tags:
        - pets
      summary: Create
      operationId: create_api_v1_pets__post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetPayload'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/v1/pets/{pet_id}:
    get:
      tags:
        - pets
      summary: Get
      operationId: get_api_v1_pets__pet_id__get
      parameters:
        - name: pet_id
          in: path
          required: true
          schema:
            type: integer
            title: Pet Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'

components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    Pet:
      properties:
        id:
          type: integer
          title: Id
        name:
          type: string
          title: Name
        age:
          type: integer
          title: Age
        type:
          type: string
          title: Type
      type: object
      required:
        - id
        - name
        - age
        - type
      title: Pet
    PetPayload:
      properties:
        name:
          type: string
          title: Name
        age:
          type: integer
          title: Age
        type:
          type: string
          title: Type
      type: object
      required:
        - name
        - age
        - type
      title: PetPayload
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
